version: "3"
services:
  keeper-core-api:
    image: "ncarlier/keeper-core-api:latest"
    restart: always
    env_file: etc/keeper-core-api.env
    volumes:
      - ./var/config:/var/opt/app/config
      - ./var/storage:/var/opt/app/storage
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
    depends_on:
      - redis
      - mongo
      - elasticsearch
    labels:
      - "traefik.port=3000"
      - "traefik.frontend.rule=PathPrefixStrip:/api"
  keeper-job-worker:
    image: "ncarlier/keeper-core-api:latest"
    restart: always
    env_file: etc/keeper-core-api.env
    command: run job-worker
    volumes:
      - ./var/config:/var/opt/app/config
      - ./var/storage:/var/opt/app/storage
    depends_on:
      - redis
      - mongo
      - elasticsearch
      - keeper-core-api
    labels:
      - "traefik.enable=false"
  keeper-web-app:
    image: "nginx:latest"
    restart: always
    volumes:
      - ./var/www:/var/www/html:ro
      - ./etc/default.conf:/etc/nginx/conf.d/default.conf:ro
    labels:
      - "traefik.port=80"
      - "traefik.frontend.rule=PathPrefixStrip:/keeper"
