version: "3"
services:
  #######################################
  # Core API
  #######################################
  keeper-core-api:
    image: "ncarlier/keeper-core-api:latest"
    restart: always
    env_file: etc/keeper-core-api.env
    volumes:
      - conf-data:/var/opt/app/config
      - storage-data:/var/opt/app/storage
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
    depends_on:
      - redis
      - mongo
      - elasticsearch
    labels:
      - "traefik.port=3000"
      - "traefik.frontend.rule=PathPrefixStrip:/api"

  #######################################
  # Job Worker
  #######################################
  keeper-job-worker:
    image: "ncarlier/keeper-core-api:latest"
    restart: always
    env_file: etc/keeper-core-api.env
    command: run job-worker
    volumes:
      - conf-data:/var/opt/app/config
      - storage-data:/var/opt/app/storage
    depends_on:
      - redis
      - mongo
      - elasticsearch
      - keeper-core-api
    labels:
      - "traefik.enable=false"

  #######################################
  # Web App
  #######################################
  keeper-web-app:
    build: ./dockerfiles/nginx
    image: "ncarlier/keeper-web-app-www:latest"
    restart: always
    volumes:
      - www-data:/var/www/html:ro
    labels:
      - "traefik.port=80"
      - "traefik.frontend.rule=PathPrefixStrip:/keeper"
